<?php
return ['messages'=>['ACCOMMODATION OF THE SITE'=>'საიტის აკომოდაცია','COMMITMENTS GDPR'=>'ვალდებულებები','CUSTOMER ACCOUNT'=>'მომხმარებლის ანგარიში','DATA PROCESSING'=>'მონაცემთა დამუშავება','DESCRIPTION OF SERVICES PROVIDED'=>'გაწეული მომსახურების აღწერა','G.D.I shares your personal data with:
<ul>
 	<li>The entities of G.D.I. for the purposes and under the conditions specified above.</li>
 	<li>Third-party service providers processing personal data on behalf of G.D.I. for example for payments and credit cards, shipments and deliveries, hosting, administration and management of your data, distribution – with your agreement – of e-mails.</li>
 	<li>Other third parties to the extent necessary to:</li>
 	<li>Comply with an administrative request, a court decision or applicable law.
Defend yourself against third-party claims.</li>
 	<li>Provide assistance in the prevention of fraud or investigation (e.g. counterfeiting).</li>
 	<li>Any other third party in cases where you have expressed your consent.</li>
</ul>
'=>'G.D.I უზიარებს თქვენს პერსონალურ მონაცემებს:
<ul>
 	<li>G.D.I.-ის სუბიექტებს ზემოთ მითითებული მიზნებისა და პირობების შესაბამისად.</li>
 	<li>მესამე მხარის მომსახურების მიმწოდებლებს, რომლებიც ამუშავებენ პერსონალურ მონაცემებს G.D.I.-ის სახელით, მაგალითად, გადახდებისა და საკრედიტო ბარათების, გადაზიდვებისა და მიწოდებების, თქვენი მონაცემების ჰოსტინგის, ადმინისტრირებისა და მართვის, ელექტრონული ფოსტის გავრცელების - თქვენი თანხმობით.</li>
 	<li>სხვა მესამე მხარეებს, იმ შემთხვევაში, თუ ეს აუცილებელია:</li>
 	<li>ადმინისტრაციული მოთხოვნის, სასამართლოს გადაწყვეტილების ან მოქმედი კანონმდებლობის შესასრულებლად.</li>
 	<li>დაიცავით თავი მესამე მხარის პრეტენზიებისგან.</li>
 	<li>დახმარება გაუწიეთ თაღლითობის ან გამოძიების თავიდან აცილებაში (მაგ., გაყალბება).</li>
</ul>
','G.D.I. collects your data in order to process your contact request or purchase. The required data is required for the follow-up of your request. In accordance with the Data Protection Act, you have the right to access, rectify and delete your data. You may also object, for a legitimate reason, to the use of your data. Only you can exercise these rights on your own data by contacting: G.D.I., Correspondent Informatique et libertés, 88 bis, rue Michel Ange, 75016 Paris or gisele.online@gisele-delorme.com , specifying in the subject of the letter “Right of persons” and attaching the copy of your proof of identity.'=>'G.D.I. აგროვებს თქვენს მონაცემებს თქვენი საკონტაქტო მოთხოვნის ან შესყიდვის დასამუშავებლად. საჭირო მონაცემები საჭიროა თქვენი მოთხოვნის შემდგომი განხილვისთვის. მონაცემთა დაცვის შესახებ კანონის შესაბამისად, თქვენ გაქვთ თქვენს მონაცემებზე წვდომის, მათზე კორექტირების და წაშლის უფლება. თქვენ ასევე შეგიძლიათ გააპროტესტოთ თქვენი მონაცემების გამოყენება ლეგიტიმური მიზეზით. მხოლოდ თქვენ შეგიძლიათ განახორციელოთ ეს უფლებები თქვენს მონაცემებზე დაკავშირების გზით: G.D.I., Correspondent Informatique et libertés, 88 bis, rue Michel Ange, 75016 Paris ან gisele.online@gisele-delorme.com, წერილის სათაურში მიუთითეთ „პირთა უფლებები“ და დაურთეთ თქვენი პირადობის დამადასტურებელი დოკუმენტის ასლი.','G.D.I. undertakes to respect the confidentiality of data concerning Buyers. This privacy policy describes the personal data that is collected when you place an order with G.D.I. It also explains how your personal data is used, shared and protected, the choices you have in relation to your personal data and how to contact us.

We ask you for certain personal data to provide you with the products or services you request, when you place an order on the Site.
'=>'G.D.I. იღებს ვალდებულებას, პატივი სცეს მყიდველებთან დაკავშირებული მონაცემების კონფიდენციალურობას. ეს კონფიდენციალურობის პოლიტიკა აღწერს პერსონალურ მონაცემებს, რომლებიც გროვდება G.D.I-ში შეკვეთის განთავსებისას. იგი ასევე განმარტავს, თუ როგორ გამოიყენება, გაზიარდება და დაცულია თქვენი პერსონალური მონაცემები, რა არჩევანი გაქვთ თქვენს პერსონალურ მონაცემებთან დაკავშირებით და როგორ დაგვიკავშირდეთ.

ჩვენ გთხოვთ გარკვეულ პერსონალურ მონაცემებს, რათა მოგაწოდოთ თქვენს მიერ მოთხოვნილი პროდუქტები ან მომსახურება, როდესაც შეკვეთას განათავსებთ საიტზე.
','HYPERLINKS'=>'HYPERLINKS','INTELLECTUAL PROPERTY AND COUNTERFEITS'=>'ინტელექტუალური საკუთრება და ფალსიფიცირებული პროდუქცია','If you consent, your data is subject to automated processing to promote our actions by e-mail. They are kept for a maximum of five years from the last contact from you or your unsubscription. In accordance with the amended Data Protection Act of 6 January 1978, you have the right to access, rectify, delete and portable your data that you can exercise by contacting gisele.online@gisele-delorme.com.'=>'თქვენი თანხმობის შემთხვევაში, თქვენი მონაცემები დაექვემდებარება ავტომატიზირებულ დამუშავებას ჩვენი ქმედებების ელექტრონული ფოსტით ხელშეწყობის მიზნით. ისინი ინახება თქვენთან ბოლო კონტაქტიდან ან გამოწერის გაუქმებიდან მაქსიმუმ ხუთი წლის განმავლობაში. 1978 წლის 6 იანვრის შესწორებული მონაცემთა დაცვის შესახებ კანონის შესაბამისად, თქვენ გაქვთ თქვენს მონაცემებზე წვდომის, მათი გასწორების, წაშლის და გადატანის უფლება, რომლის განხორციელებაც შეგიძლიათ gisele.online@gisele-delorme.com-ზე დაკავშირების გზით.','Intra-Community VAT Number : FR94883094591'=>'საზოგადოების შიდა დღგ-ს ნომერი: FR94883094591','NEWSLETTER'=>'გაზეთი','The collection by G.D.I. of personal information when creating a customer account was declared to the CNIL under the number DPO-84171.'=>'მომხმარებლის ანგარიშის შექმნისას G.D.I.-ის მიერ პერსონალური ინფორმაციის შეგროვება განხორციელდა CNIL-ში DPO-84171 ნომრით.','The owner of the site owns the intellectual property rights or holds the rights of use on all the elements accessible on the site, including text, images, graphics, logo, icons, sounds, software.
Any reproduction, representation, modification, publication, total or partial adaptation of the elements of the site, whatever the means or the process used, is prohibited, unless written authorization prior to the email: gisele.online@gisele-delorme.com .
Any unauthorized use of the site or any of its elements will be considered to constitute an infringement and prosecuted in accordance with the provisions of articles L.335-2 and following of the Intellectual Property Code.'=>'საიტის მფლობელი ფლობს ინტელექტუალური საკუთრების უფლებებს ან ფლობს საიტზე ხელმისაწვდომ ყველა ელემენტზე, მათ შორის ტექსტზე, სურათებზე, გრაფიკაზე, ლოგოზე, ხატულებზე, ხმებზე, პროგრამულ უზრუნველყოფაზე გამოყენების უფლებას.<br>საიტის ელემენტების ნებისმიერი რეპროდუცირება, წარმოდგენა, მოდიფიკაცია, გამოქვეყნება, სრული ან ნაწილობრივი ადაპტაცია, გამოყენებული საშუალებებისა თუ პროცესის მიუხედავად, აკრძალულია, თუ წინასწარ არ არის წერილობითი ნებართვა გაგზავნილი ელექტრონული ფოსტით: gisele.online@gisele-delorme.com.<br>საიტის ან მისი რომელიმე ელემენტის ნებისმიერი უნებართვო გამოყენება ჩაითვლება დარღვევად და დაისჯება ინტელექტუალური საკუთრების კოდექსის L.335-2 და შემდგომი მუხლების დებულებების შესაბამისად.','The purpose of the website www.gisele-delorme.com is to inform about the products and to allow online purchase. The owner of the site strives to provide the information as accurate as possible.

However, it cannot be held responsible for omissions, inaccuracies and deficiencies in the update, whether by it or by the third party partners who provide this information.

All the information offered on the site is given as an indication, is not exhaustive and is likely to evolve. They are given subject to changes that have been made since they were posted online.'=>'ვებგვერდის www.gisele-delorme.com მიზანია პროდუქციის შესახებ ინფორმაციის მიწოდება და ონლაინ შესყიდვების განხორციელება. საიტის ცდილობს,მაქსიმალურად ზუსტი ინფორმაციის მიწოდებას.

თუმცა, ის არ არის პასუხისმგებელი განახლებაში არსებულ გამოტოვებებზე, უზუსტობებსა და ნაკლოვანებებზე, იქნება ეს მისი ან ამ ინფორმაციის მიმწოდებელი მესამე მხარის პარტნიორების მიერ.

საიტზე შემოთავაზებული ყველა ინფორმაცია მოცემულია მითითების სახით, არ არის ამომწურავი და შესაძლოა განვითარდეს. ისინი მოცემულია ონლაინ განთავსების შემდეგ განხორციელებული ცვლილებების გათვალისწინებით.3','The site gisele-delorme.com points to many other websites. G.D.I. cannot be held responsible for the content and privacy policy of these sites. G.D.I. cannot be held responsible for any direct or indirect damages that would result from their use: in particular from access to these sites and the sites linked to these sites, and for damages, non-limiting, financial or commercial damage, loss of exploitation, loss of data, even if we have been able to be notified in advance.'=>'საიტი gisele-delorme.com სხვა მრავალ ვებსაიტზე მიუთითებს. G.D.I. არ არის პასუხისმგებელი ამ საიტების შინაარსსა და კონფიდენციალურობის პოლიტიკაზე. G.D.I. არ არის პასუხისმგებელი მათი გამოყენების შედეგად მიყენებულ ნებისმიერ პირდაპირ ან ირიბ ზიანზე: კერძოდ, ამ საიტებზე და მათთან დაკავშირებულ საიტებზე წვდომიდან, ასევე ზარალზე, არაშემზღუდავ, ფინანსურ ან კომერციულ ზიანზე, ექსპლუატაციის დაკარგვაზე, მონაცემთა დაკარგვაზე, მაშინაც კი, თუ წინასწარ შეგვეძლო ამის შესახებ შეტყობინების მიღება.','The site is declared to the CNIL (https://www.cnil.fr/) under number DPO-84171.'=>'საიტი CNIL-ისთვის (https://www.cnil.fr/) რეგისტრირებულია DPO-84171 ნომრით.','The site is hosted in France by the company OVH – 2, rue Kellermann – 59100 Roubaix – France.'=>'საიტს საფრანგეთში მართავს კომპანია OVH – 2, rue Kellermann – 59100 Roubaix – France.','The website www.gisele-delorme.com is edited and operated by the company G.D.I, a simplified joint-stock company with a capital of 30 000 € registered with the RCS of Paris under the number 883 094 591 000 12, and domiciled at 88 bis, rue Michel Ange 75016 PARIS.'=>'ვებსაიტს www.gisele-delorme.com რედაქტირებულია და მართავს კომპანია G.D.I, გამარტივებული სააქციო საზოგადოება 30 000 ევროს კაპიტალით, რეგისტრირებულია პარიზის RCS-ში ნომრით 883 094 591 000 12 და მდებარეობს შემდეგ მისამართზე: 88 bis, rue Michel Ange 75016 PARIS.','These personal data include your:
<ul>
 	<li>Contact information such as email, phone number and shipping and delivery address.</li>
 	<li>Your purchase and payment history.</li>
</ul>
'=>'ეს პერსონალური მონაცემები მოიცავს თქვენს:
<ul>
 	<li>საკონტაქტო ინფორმაციას, როგორიცაა ელექტრონული ფოსტა, ტელეფონის ნომერი და მიწოდების მისამართი.</li>
 	<li>თქვენი შესყიდვებისა და გადახდის ისტორია.</li>
</ul>
','To reach G.D.I., you can write to gisele.online@gisele-delorme.com or directly on the Site via the CONTACT“CONTACT” section by stating your contact details and the reason for your request.'=>'G.D.I.-სთან დასაკავშირებლად, შეგიძლიათ მისწეროთ gisele.online@gisele-delorme.com-ზე ან პირდაპირ საიტზე კონტაქტის „კონტაქტი“ განყოფილების მეშვეობით, თქვენი საკონტაქტო ინფორმაციის და თქვენი მოთხოვნის მიზეზის მითითებით.','We collect this information in order to process your orders. They are kept for one year and are not reused for other purposes, nor communicated to third parties. To exercise your right of access, modification, deletion and portability of data concerning you, you can write to gisele.online@gisele-delorme.com.'=>'We collect this information in order to process your orders. ჩვენ ამ ინფორმაციას თქვენი შეკვეთების დასამუშავებლად ვაგროვებთ. ის ერთი წლის განმავლობაში ინახება და არ გამოიყენება სხვა მიზნებისთვის და არც გადაეცემა მესამე პირებს. თქვენთან დაკავშირებულ მონაცემებზე წვდომის, მათი შეცვლის, წაშლისა და პორტაბელურობის უფლების განსახორციელებლად, შეგიძლიათ მოგვწეროთ შემდეგ მისამართზე: gisele.online@gisele-delorme.com.','When we use the services of third-party providers, we enter into contracts that require them to implement appropriate technical and organizational measures to protect your personal data.

For credit card payments, the data is not kept.

We may also transfer your personal data in the event that we assign or transfer all or part of our business or assets (including in the case of a reorganization, assignment, dissolution or liquidation)'=>'ნებისმიერი სხვა მესამე მხარე იმ შემთხვევებში, როდესაც თქვენ გამოხატეთ თქვენი თანხმობა.<br>როდესაც ჩვენ ვიყენებთ მესამე მხარის პროვაიდერების მომსახურებას, ჩვენ ვდებთ კონტრაქტებს, რომლებიც ავალდებულებს მათ განახორციელონ შესაბამისი ტექნიკური და ორგანიზაციული ზომები თქვენი პერსონალური მონაცემების დასაცავად.<br>საკრედიტო ბარათით გადახდების შემთხვევაში, მონაცემები არ ინახება.<br>ჩვენ ასევე გადავცემთ თქვენს პერსონალურ მონაცემებს იმ შემთხვევაში, თუ ჩვენ ვახორციელებთ ჩვენი ბიზნესის ან აქტივების სრულად ან ნაწილობრივ დათმობას ან გადაცემას (მათ შორის, რეორგანიზაციის, დათმობის, დაშლის ან ლიკვიდაციის შემთხვევაში).','YOUR RIGHTS'=>'თქვენი უფლებები','You have the right to request: access to your personal data, rectification of your personal data, or the erasure or limitation of your personal data in certain circumstances provided for by applicable law. These rights are not absolute. Your consent to the processing of your personal data when you visit the Site, may be revoked by you at any time.

If you wish to request a copy of your personal data or exercise any of your rights, please contact us at gisele.online@gisele-delorme.com
'=>'თქვენ გაქვთ უფლება მოითხოვოთ: თქვენს პერსონალურ მონაცემებზე წვდომა, თქვენი პერსონალური მონაცემების გასწორება ან თქვენი პერსონალური მონაცემების წაშლა ან შეზღუდვა მოქმედი კანონმდებლობით გათვალისწინებულ გარკვეულ შემთხვევებში. ეს უფლებები აბსოლუტური არ არის. საიტზე შესვლისას თქვენი პერსონალური მონაცემების დამუშავებაზე თქვენი თანხმობა შეიძლება ნებისმიერ დროს გააუქმოთ.

თუ გსურთ თქვენი პერსონალური მონაცემების ასლის მოთხოვნა ან თქვენი რომელიმე უფლების გამოყენება, გთხოვთ, დაგვიკავშირდეთ ელექტრონულ ფოსტაზე gisele.online@gisele-delorme.com
']];
