<?php
return ['messages'=>['
<p style="text-align: center;">Madame Delorme reminded us that “to be beautiful, a woman must feel good about herself”. This approach shapes our vision of beauty. Our vision is based on realistic, achievable promises…</p>
'=>'
<p style="text-align: center;">მადამ დელორმმა შეგვახსენა - „იმისათვის, რომ ქალი გამოიყურებოდეს ლამაზად, იგი თავს უნდა გრძნობდეს კარგად!“. სწორედ ეს მიდგომა აყალიბებს ჩვენს ხედვას სილამაზის შესახებ. ჩვენი ხედვა ეფუძნება მხოლოდ რეალისტურ, მიღწევად დაპირებებს.</p>
','
<p style="text-align: center;">Since 1977, the Gisèle Delorme method has made it possible to create a made-to-measure treatment for every skin condition, for all ages. The exceptional results it delivers on the skin are unparalleled, placing Gisèle Delorme in a class of its own in the world of professional skin care…</p>
'=>'
<p style="text-align: center;">1977 წლიდან Gisèle Delorm მიერ შემუშავებულმა მეთოდიკამ შესაძლებელი გახადა ყველანაირი ასაკისა და ტიპის კანისათვის ინდივიდუალური მიდგომებით მკუნალობის შესაძლებლობა. კანის მოვლსთან დაკავშირებული შედეგები იმდენად გასაოცარია, რომ Gisèle Delorm მრავალი წლის განმავლობაში პროფესიონალური კანის მოვლის სამყაროში განსაკუთრებული ადგილი უკავია.</p>
','#'=>'#','#giseledelormeparis'=>'#giseledelormeparis','FOLLOW-US'=>'გამოგვყევით','GISÈLE DELORME’S VISION OF BEAUTY- GISÈLE DELORME’S'=>'სილამაზის ხედვა','INSTAGRAM'=>'INSTAGRAM','SHOP OUR PRODUCTS'=>'იყიდეთ ჩვენი პროდუქცია','THE GISÈLE DELORME FACE LYMPHATIC DRAINAGE TRAINING -THE GISÈLE DELORME'=>'სახის ლიმფური დრენაჟის ტრენინგი','THE GISÈLE DELORME SKIN CARE METHOD - GISÈLE DELORME'=>'კანის მოვლის მეთოდიკა','TO KNOW MORE'=>'შეიტყვეთ მეტი','With the Gisèle Delorme Paris skincare method, you’ll move into a new dimension and become a recognized and appreciated derma-therapist. You’ll provide unparalleled skincare treatments. Your knowledge and know-how will give you a lasting competitive edge, and the reason to add value to your services.'=>'Gisèle Delorme Paris სახის მოვლის განსაკუთრებული მეთოდიკის შესწავლით თქვენ შესაძლებლობა გეძლევათ გადახვიდეთ სულ სხვა განზომილებაში და გახდეთ დაფასებული დერმატო-თერაპევტი. ჩვენ გთავაზობთ სახის კანის მოვლის უპრეცედენტო და უნიკალურ მეთოდიკას და პროცედურებს. თქვენს მიერ მიღებული ცოდნა და ნოუ-ჰაუ მოგცემთ მდგრად კონკურენტულ უპირატესობას და თქვენი მომსახურების ღირებულების გაზრდის რეალურ შანსსა და შესაძლებლობას.','https://www.instagram.com/giseledelormeparis/?hl=fr'=>'https://www.instagram.com/giseledelormeparis/?hl=fr']];
