<?php
return ['messages'=>['
<p style="text-align: center;">Madame Delorme reminded us that “to be beautiful, a woman must feel good about herself”. This approach shapes our vision of beauty. Our vision is based on realistic, achievable promises…</p>
'=>'
<p style="text-align: center;">Madame Delorme, rappelait que « Pour être belle, une femme doit se sentir bien dans sa peau ». Cette approche imprime notre vision de la beauté. La santé de la peau fait sa beauté et celle ou celui qu’elle enveloppe. Notre vision s’appuie sur des promesses réalistes et atteignables</p>
','
<p style="text-align: center;">Since 1977, the Gisèle Delorme method has made it possible to create a made-to-measure treatment for every skin condition, for all ages. The exceptional results it delivers on the skin are unparalleled, placing Gisèle Delorme in a class of its own in the world of professional skin care…</p>
'=>'
<p style="text-align: center;">Depuis 1977, la méthode Gisèle Delorme permet de composer un soin sur-mesure pour chaque condition de peau, à tout âge. Les résultats exceptionnels sur la qualité de peau qu’elle procure sont incomparables et place Gisèle Delorme dans une catégorie à part dans le monde du soin professionnel.</p>
','#'=>'#','#giseledelormeparis'=>'#giseledelormeparis','FOLLOW-US'=>'SUIVEZ-NOUS','GISÈLE DELORME’S VISION OF BEAUTY- GISÈLE DELORME’S'=>'LA VISION DE LA BEAUTÉ DE GISÈLE DELORME','INSTAGRAM'=>'INSTAGRAM','SHOP OUR PRODUCTS'=>'ACCÉDER AU CATALOGUE','THE GISÈLE DELORME FACE LYMPHATIC DRAINAGE TRAINING -THE GISÈLE DELORME'=>'LA FORMATION AU DRAINAGE LYMPHATIQUE GISELE DELORME VISAGE','THE GISÈLE DELORME SKIN CARE METHOD - GISÈLE DELORME'=>'LA MÉTHODE DE SOIN GISÈLE DELORME','TO KNOW MORE'=>'EN SAVOIR PLUS','With the Gisèle Delorme Paris skincare method, you’ll move into a new dimension and become a recognized and appreciated derma-therapist. You’ll provide unparalleled skincare treatments. Your knowledge and know-how will give you a lasting competitive edge, and the reason to add value to your services.'=>'Avec la formation à la méthode de soin Gisèle Delorme Paris, vous évoluerez vers une nouvelle dimension et deviendrez une derma-thérapeute reconnue et appréciée. Vous prodiguerez des soins de la peau à très forte valeur ajoutée. Vos connaissances et votre savoir-faire vous donneront un avantage concurrentiel durable, et la raison d’ajouter de la valeur à vos services.','https://www.instagram.com/giseledelormeparis/?hl=fr'=>'https://www.instagram.com/giseledelormeparis/?hl=fr']];
